# Update WordInfo\capacity.txt

$PSDefaultParameterValues["*:Encoding"] = "UTF8"

# Get the DLC folders (including Core)
$dlcs = Get-ChildItem -Directory | Where-Object { Test-Path -Path (Join-Path -Path $_.FullName -ChildPath "DefInjected") }

# Paths of the XML files in which the words should be searched
# and the regex pattern to match the elements
$items = [ordered]@{
"DefInjected\PawnCapacityDef\*" = "\w+\.label.*?"
}

# Formats
$formats =  @(
"unfähig für {0}" # IncapableOfCapacity, AbilityDisabledNoCapacity, CannotMissingHealthActivities, RequiredCapacity
"Körperfunktion '{0}'" # KilledCapacity tale
)

# Header line for capacity.txt
$header = @(
"KEY"       # key, normal capacity label
"1_OUT"     # index #1, other outcome
)

# Usage description. Using comment flag "//" instead of the recommended "#" as RW doesn't support it.
$comments = @"
// Auto-generated by $($MyInvocation.MyCommand.Name)
// Capacity text improvements
// Usage syntax: {lookup: TEXT; FILE_NO_EXT; INDEX}
// TEXT is the key to access a row.
// FILE_NO_EXT is the file in which TEXT should be looked up. Omit the extension.
// INDEX determines the column to be used. Can be omitted if you need index 1.
// For example, {lookup: {0}; capacity; 1} looks up 1_OUT.
// ---
"@

# Enumerate DLC folders (including Core)
$tempFile = New-Item "$env:temp\$([GUID]::NewGuid()).txt"
foreach ($dlc in $dlcs)
{
  Clear-Content -Path $tempFile
  Set-Location -Path "$PSScriptRoot\$dlc"
  $declineFile = "WordInfo\capacity.txt"

  # Create a hash table of nominative words
  $HashTable = new-object System.Collections.Hashtable
  $declineFileLines = @()
  if (test-path $declineFile) {
    $declineFileLines = Get-Content -Path $declineFile
    Remove-Item $declineFile
  }
  foreach ($line in ($declineFileLines | ConvertFrom-Csv -Delimiter ";" -Header $header))
  {
    if ($line.KEY.substring(0, 2) -eq "//") { continue } # skip "//" comments
    $fields = $line.PSObject.Properties.Value -join ";"
    $fields = $fields -replace "(?<=;);" # remove empty fields for clarity and reducing file size
    $HashTable[$line.KEY] = $fields
  }

  # Search words in the XML files and add them to a temp file
  $items.GetEnumerator() | ForEach-Object {
    $paths = ($($_.Key) -split ',').Trim()
    $pattern = $($_.Value)
    $elements = @()
    $ps = @()
    foreach ($path in $paths) {
      if (!(test-path $path)) { continue } # skip non-existing paths
      $ps += $path
      $elements += Get-Content -Path $path -Filter "*.xml" | Select-String -Pattern "<($pattern)>(?<value>.*?)</\1>" -All
    }
    if ($elements.Count -eq 0) { return } # skip if no elements found
    "// $($ps -join ', ') ($pattern)" >> $tempFile # categorize capacity.txt by paths
    # enumerate lines
    $tempFileLines = @()
    foreach ($format in $formats) {
      foreach ($element in $elements) {
        $element_value = $element.matches[0].groups["value"]
        $tempFileLines += $format -f $element_value
      }
    }
    Add-Content -Path $tempFile -Value ($tempFileLines | Sort-Object)
  }

  # Merge the temp file with capacity.txt
  $tempFileLines = Get-Content $tempFile
  if ($tempFileLines.Count -eq 0) { continue } # skip if temp file is empty
  $declineFileLines = @($header -join ";")
  $declineFileLines += $comments
  foreach ($line in ($tempFileLines | Select-Object -Unique))
  {
    if ($line.substring(0, 2) -eq "//") {
      $declineFileLines += $line
    } elseif ($HashTable.ContainsKey($line)) {
      $declineFileLines += $HashTable[$line]
    } else {
      $declineFileLines += $line + ";"
    }
  }
  New-Item $declineFile -Force | Out-Null
  Set-Content -Path $declineFile -Value $declineFileLines
}
Set-Location -Path $PSScriptRoot
Remove-Item $tempFile
