# Update WordInfo\plural.txt

$PSDefaultParameterValues["*:Encoding"] = "UTF8"

# Get the DLC folders (including Core)
$dlcs = Get-ChildItem -Directory | Where-Object { Test-Path -Path (Join-Path -Path $_.FullName -ChildPath "DefInjected") }

# Paths of the XML files in which the words should be searched
# and the regex pattern to match the elements
$items = [ordered]@{
"DefInjected\OrderedTakeGroupDef\*" = ".+\.label" # MaxPickUpAllowed
"DefInjected\PsychicRitualRoleDef\*" = ".+\.label" # MaxPawnsPerRole, categoryLabel
"DefInjected\RitualBehaviorDef\*" = ".+\.label" # MessageLordJobNeedsAtLeastNumRolePawn, ritual dialog
"DefInjected\ThingDef\Apparel_*.xml, DefInjected\ThingDef\RangedSpecial.xml, DefInjected\ThingDef\Weapons_Ranged.xml" = ".+\.chargeNoun" # ReloadRemainingChargesMultipler, ReloadChargesRemaining, ReloadMaxCharges, ReloadPerCharge, CommandReload_NoCharges
"DefInjected\ThingDef\Buildings_Furniture.xml" = "Blackboard\.label" # StatsReport_Connected
"DefInjected\ThingDef\Buildings_Mech*" = "\w+\.label" # ThreatReward_MechPods_MiscReward, Util_MechCluster etc.
"DefInjected\ThingDef\Buildings_Natural.xml" = "Mineable\w+\.label" # MineralRich, MineralRichDescription
"DefInjected\ThingDef\Buildings_Misc.xml" = "TransportPod\.label" # LoadTransporters
"DefInjected\ThingDef\Buildings_PsychicRituals.xml" = ".+\.label" # psychic ritual dialog
"DefInjected\ThingDef\Items_Resource_Manufactured.xml" = "Wastepack\.label" # CommandAutoLoad, CommandEjectContents, ThingsProduced, ContainedThings
"DefInjected\ThingDef\Plants_*" = ".+\.label" # MessagePlantIncompatibleWithRoof, LetterCropBlight
"DefInjected\ThingDef\Various_Stone.xml" = "Chunk\w+\.label" # DeepDrillExhausted
"Keyed\FloatMenu.xml" = "Deity" # DeitiesRequired
}

# Usage description. Using comment flag "//" instead of the recommended "#" as RW doesn't support it.
$comments = @"
// Auto-generated by $($MyInvocation.MyCommand.Name)
// Ingame pluralization use this file automatically.
// For declension, use plural_decline.txt
// ---
"@

# Enumerate DLC folders (including Core)
$tempFile = New-Item "$env:temp\$([GUID]::NewGuid()).txt"
foreach ($dlc in $dlcs)
{
  Clear-Content -Path $tempFile
  Set-Location -Path "$PSScriptRoot\$dlc"
  $outputFile = "WordInfo\plural.txt"

  # Create a hash table of singular nominative words
  $HashTable = new-object System.Collections.Hashtable
  $outputFileLines = @()
  if (test-path $outputFile) {
    $outputFileLines = Get-Content -Path $outputFile
    Remove-Item $outputFile
  }
  foreach ($line in ($outputFileLines | ConvertFrom-Csv -Delimiter ";" -Header @("s", "p")))
  {
    if ($line.s.substring(0, 2) -eq "//") { continue } # skip "//" comments
    $fields = $line.PSObject.Properties.Value -join ";"
    $fields = $fields -replace "(?<=;);" # remove empty fields for clarity and reducing file size
    $HashTable[$line.s] = $fields
  }

  # Search words in the XML files and add them to a temp file
  $items.GetEnumerator() | ForEach-Object {
    $paths = ($($_.Key) -split ',').Trim()
    $pattern = $($_.Value)
    $elements = @()
    $ps = @()
    foreach ($path in $paths) {
      if (!(test-path $path)) { continue } # skip non-existing paths
      $ps += $path
      $elements += Get-Content -Path $path -Filter "*.xml" | Select-String -Pattern "<($pattern)>(?<value>.*?)</\1>" -All
    }
    if ($elements.Count -eq 0) { return } # skip if no elements found
    "// $($ps -join ', ') ($pattern)" >> $tempFile # categorize by paths
    # enumerate lines
    $tempFileLines = @()
    foreach ($element in $elements) { $tempFileLines += $element.matches[0].groups["value"] }
    Add-Content -Path $tempFile -Value ($tempFileLines | Sort-Object)
  }

  # Merge the temp file with the output file
  $tempFileLines = Get-Content $tempFile
  if ($tempFileLines.Count -eq 0) { continue } # skip if temp file is empty
  $outputFileLines = @($comments)
  foreach ($line in ($tempFileLines | Select-Object -Unique))
  {
    if ($line.substring(0, 2) -eq "//") {
      $outputFileLines += $line
    } elseif ($HashTable.ContainsKey($line)) {
      $outputFileLines += $HashTable[$line]
    } else {
      $outputFileLines += $line + ";"
    }
  }
  New-Item $outputFile -Force | Out-Null
  Set-Content -Path $outputFile -Value $outputFileLines
}
Set-Location -Path $PSScriptRoot
Remove-Item $tempFile
