# Update WordInfo\compound.txt

$PSDefaultParameterValues["*:Encoding"] = "UTF8"

# Get the DLC folders (including Core)
$dlcs = Get-ChildItem -Directory | Where-Object { Test-Path -Path (Join-Path -Path $_.FullName -ChildPath "DefInjected") }

# Paths of the XML files in which the words should be searched
# and the regex pattern to match the elements
$items = [ordered]@{
"DefInjected\FactionDef\*" = "\w+\.pawnSingular"
"DefInjected\ThingDef\Plants_*" = "\w+\.label"
"DefInjected\*\Races_*" = "\w+\.label" # Hospitality_Animals, MeatLabel
}

# Header line for the output file
$header = @(
"NOM"       # key, nominative
"1_COM_PRE" # index #1, compound prefix
)

# Usage description. Using comment flag "//" instead of the recommended "#" as RW doesn't support it.
$comments = @"
// Auto-generated by $($MyInvocation.MyCommand.Name)
// Compound words (as prefix), e.g. Piraten in Piratengruppe
// Usage syntax: {lookup: TEXT; FILE_NO_EXT; INDEX}
// TEXT is the key to access a row.
// FILE_NO_EXT is the file in which TEXT should be looked up. Omit the extension.
// INDEX determines the column to be used. Can be omitted if you need index 1.
// For example, {lookup: {0}; compound; 1} looks up 1_COM_PRE.
// ---
"@

# Enumerate DLC folders (including Core)
$tempFile = New-Item "$env:temp\$([GUID]::NewGuid()).txt"
foreach ($dlc in $dlcs)
{
  Clear-Content -Path $tempFile
  Set-Location -Path "$PSScriptRoot\$dlc"
  $outputFile = "WordInfo\compound.txt"

  # Create a hash table of indefinite nominative words
  $HashTable = new-object System.Collections.Hashtable
  $outputFileLines = @()
  if (test-path $outputFile) {
    $outputFileLines = Get-Content -Path $outputFile
    Remove-Item $outputFile
  }
  foreach ($line in ($outputFileLines | ConvertFrom-Csv -Delimiter ";" -Header $header))
  {
    if ($line.NOM.substring(0, 2) -eq "//") { continue } # skip "//" comments
    $fields = $line.PSObject.Properties.Value -join ";"
    $fields = $fields -replace "(?<=;);" # remove empty fields for clarity and reducing file size
    $HashTable[$line.NOM] = $fields
  }

  # Search words in the XML files and add them to a temp file
  $items.GetEnumerator() | ForEach-Object {
    $paths = ($($_.Key) -split ',').Trim()
    $pattern = $($_.Value)
    $elements = @()
    $ps = @()
    foreach ($path in $paths) {
      if (!(test-path $path)) { continue } # skip non-existing paths
      $ps += $path
      $elements += Get-Content -Path $path -Filter "*.xml" | Select-String -Pattern "<($pattern)>(?<value>.*?)</\1>" -All
    }
    if ($elements.Count -eq 0) { return } # skip if no elements found
    "// $($ps -join ', ') ($pattern)" >> $tempFile # categorize by paths
    # enumerate lines
    $tempFileLines = @()
    foreach ($element in $elements) { $tempFileLines += $element.matches[0].groups["value"] }
    Add-Content -Path $tempFile -Value ($tempFileLines | Sort-Object)
  }

  # Merge the temp file with the output file
  $tempFileLines = Get-Content $tempFile
  if ($tempFileLines.Count -eq 0) { continue } # skip if temp file is empty
  $outputFileLines = @($header -join ";")
  $outputFileLines += $comments
  foreach ($line in ($tempFileLines | Select-Object -Unique))
  {
    if ($line.substring(0, 2) -eq "//") {
      $outputFileLines += $line
    } elseif ($HashTable.ContainsKey($line)) {
      $outputFileLines += $HashTable[$line]
    } else {
      $outputFileLines += $line + ";"
    }
  }
  New-Item $outputFile -Force | Out-Null
  Set-Content -Path $outputFile -Value $outputFileLines
}
Set-Location -Path $PSScriptRoot
Remove-Item $tempFile
