function Get-DLCs {
  Get-ChildItem -Directory | Where-Object {
    Test-Path (Join-Path $_.FullName "DefInjected")
  }
}

function New-CommentBlock {
  param($ScriptFile, $Description, $ExampleFile, $ExampleColName)
  # Use comment flag "//" instead of the CSV‑standard "#" as RW doesn't support it.
@"
// Auto-generated by $ScriptFile
// $Description
// Usage syntax: {lookup: TEXT; FILE_NO_EXT; INDEX}
// TEXT is the key to access a row.
// FILE_NO_EXT is the file in which TEXT should be looked up. Omit the extension.
// INDEX determines the column to be used. Can be omitted if you need index 1.
// For example, {lookup: {0}; $ExampleFile; 1} looks up $ExampleColName.
// ---
"@
}

function New-HashTable {
  param($Lines)
  $HashTable = New-Object System.Collections.Hashtable
  foreach ($Line in $Lines) {
    $Fields = $Line -Split ";"
    if (Test-Comment $Fields[0]) { continue }
    $HashTable[$Fields[0]] = $Fields
  }
  return $HashTable
}

function Scan-XML {
  param($Rules)
  $TempFileLines = @()
  $Rules.GetEnumerator() | ForEach-Object {
    $Paths = ($_.Key -Split ',').Trim()
    $Pattern = $_.Value
    $Elements = @()
    $MatchedPaths = @()
    foreach ($Path in $Paths) {
      if (!(Test-Path $Path)) { continue } # Skip non-existing paths
      $MatchedPaths += $Path
      $Elements += Get-Content -Path $Path -Filter "*.xml" |
        Select-String -Pattern "<($Pattern)>(?<value>.*?)</\1>" -All
    }
    if ($Elements.Count -eq 0) { return } # Skip if no elements found
    $TempFileLines += "// $($MatchedPaths -Join ', ') ($Pattern)" # Categorize by paths
    $CategoryLines = @()
    foreach ($Element in $Elements) {
      $Value = $Element.Matches[0].Groups["value"].Value
      $CategoryLines += $Value
    }
    $TempFileLines += ($CategoryLines | Sort-Object)
  }
  return $TempFileLines
}

function Test-Comment {
  param($String)
  return ($String.StartsWith("//") -or $String.StartsWith("#"))
}

function Merge-Output {
  param($TempLines, $OutputFileLines, $ColNames, $CommentBlock)
  $HashTable = New-HashTable -Lines $OutputFileLines
  $FieldsCountTotal = $ColNames.Count
  $OutputFileLinesNew = @()
  $OutputFileLinesNew += $ColNames -Join ";"
  $OutputFileLinesNew += $CommentBlock
  foreach ($Line in ($TempLines | Select-Object -Unique)) {
    if (Test-Comment $Line) {
      $OutputFileLinesNew += $Line
    } elseif ($HashTable.ContainsKey($Line)) {
      $OutputFileLinesNew += $HashTable[$Line] -Join ";" -Replace "(?<=;);"
      # The replacement removes empty fields for clarity and reducing file size
    } else {
      $FieldsCountCurrent = ($Line -Split ";").Count
      if ($FieldsCountCurrent -lt $FieldsCountTotal) {
        $OutputFileLinesNew += $Line + ";"
      } else {
        $OutputFileLinesNew += $Line
      }
    }
  }
  return $OutputFileLinesNew
}

function Update-OutputFile {
  param($OutputFile, $ScanRules, $ColNames, $CommentBlock, $PostProcCallback)
  foreach ($DLC in Get-DLCs) { # Enumerate DLC folders (including Core)
    Set-Location -Path "$PSScriptRoot\$DLC"
    $OutputFileLines = @()
    if (Test-Path $OutputFile) {
      $OutputFileLines = Get-Content -Path $OutputFile
      Remove-Item $OutputFile
    }
    # Scan for words in the XML files and add them to the temp file
    $TempLines = Scan-XML -Rules $ScanRules
    if ($TempLines.Count -eq 0) { continue }
    if ($PostProcCallback) {
      $TempLines = & $PostProcCallback $TempLines $DLC.ToString()
    }
    # Merge the temp file with the output file
    $OutputFileLinesNew = Merge-Output `
      -TempLines $TempLines `
      -OutputFileLines $OutputFileLines `
      -ColNames $ColNames `
      -CommentBlock $CommentBlock
    Set-Content -Path $OutputFile -Value $OutputFileLinesNew
  }
  Set-Location -Path $PSScriptRoot
}

function Format-Lines {
  param($Lines, $Formats)
  $FormattedLines = @()
  foreach ($Line in $Lines) {
    if (Test-Comment $Line) {
      $FormattedLines += $Line
    } else {
      foreach ($Format in $Formats) {
        $FormattedLines += ($Format -f $Line)
      }
    }
  }
  return $FormattedLines
}
