function Get-DLCs {
  Get-ChildItem -Directory | Where-Object {
    Test-Path (Join-Path $_.FullName "DefInjected")
  }
}

function New-CommentBlock {
  param($ScriptFile, $Description, $ExampleFile, $ExampleColName)
  # Use comment flag "//" instead of the CSV‑standard "#" as RW doesn't support it.
@"
// Auto-generated by $ScriptFile
// $Description
// Usage syntax: {lookup: TEXT; FILE_NO_EXT; INDEX}
// TEXT is the key to access a row.
// FILE_NO_EXT is the file in which TEXT should be looked up. Omit the extension.
// INDEX determines the column to be used. Can be omitted if you need index 1.
// For example, {lookup: {0}; $ExampleFile; 1} looks up $ExampleColName.
// ---
"@
}

function New-HashTable {
  param($OutputFile, $ColNames)
  $HashTable = New-Object System.Collections.Hashtable
  $OutputFileLines = @()
  if (Test-Path $OutputFile) {
    $OutputFileLines = Get-Content -Path $OutputFile
    Remove-Item $OutputFile
  }
  foreach ($Line in ($OutputFileLines | ConvertFrom-Csv -Delimiter ";" -Header $ColNames)) {
    if (Test-Comment $Line.$($ColNames[0])) { continue }
    $Fields = $Line.PSObject.Properties.Value -Join ";"
    $Fields = $Fields -Replace "(?<=;);" # Remove empty fields for clarity and reducing file size
    $HashTable[$Line.$($ColNames[0])] = $Fields
  }
  return $HashTable
}

function Scan-XML {
  param($Rules, $Formats)
  $TempFileLines = @()
  $Rules.GetEnumerator() | ForEach-Object {
    $Paths = ($_.Key -Split ',').Trim()
    $Pattern = $_.Value
    $Elements = @()
    $MatchedPaths = @()
    foreach ($Path in $Paths) {
      if (!(Test-Path $Path)) { continue } # Skip non-existing paths
      $MatchedPaths += $Path
      $Elements += Get-Content -Path $Path -Filter "*.xml" |
        Select-String -Pattern "<($Pattern)>(?<value>.*?)</\1>" -All
    }
    if ($Elements.Count -eq 0) { return } # Skip if no elements found
    $TempFileLines += "// $($MatchedPaths -Join ', ') ($Pattern)" # Categorize by paths
    $CategoryLines = @()
    foreach ($Element in $Elements) {
      $Value = $Element.Matches[0].Groups["value"].Value
      if ($Formats) {
        foreach ($Format in $Formats) {
          $CategoryLines += ($Format -f $Value)
        }
      }
      else {
        $CategoryLines += $Value
      }
    }
    $TempFileLines += ($CategoryLines | Sort-Object)
  }
  return $TempFileLines
}

function Test-Comment {
  param($String)
  return ($String.StartsWith("//") -or $String.StartsWith("#"))
}

function Merge-Output {
  param($TempLines, $HashTable, $ColNames, $CommentBlock)
  $OutputFileLines = @()
  if ($ColNames) {
    $OutputFileLines += $ColNames -Join ";"
  }
  $OutputFileLines += $CommentBlock
  foreach ($Line in ($TempLines | Select-Object -Unique)) {
    if (Test-Comment $Line) {
      $OutputFileLines += $Line
    } elseif ($HashTable.ContainsKey($Line)) {
      $OutputFileLines += $HashTable[$Line]
    } else {
      $OutputFileLines += $Line + ";"
    }
  }
  return $OutputFileLines
}

function Update-OutputFile {
  param($OutputFile, $ScanRules, $Formats, $ColNames, $CommentBlock, $ExtraLinesProvider)
  foreach ($DLC in Get-DLCs) { # Enumerate DLC folders (including Core)
    Set-Location -Path "$PSScriptRoot\$DLC"
    # Create a hash table of keys
    $HashTable = New-HashTable -OutputFile $OutputFile -ColNames $ColNames
    # Scan for words in the XML files and add them to the temp file
    $TempLines = Scan-XML -Rules $ScanRules -Formats $Formats
    if ($TempLines.Count -eq 0) { continue }
    if ($ExtraLinesProvider) {
      $ExtraLines = & $ExtraLinesProvider
      if ($ExtraLines -and $ExtraLines.Count -gt 0) {
        $TempLines += $ExtraLines
      }
    }
    # Merge the temp file with the output file
    $OutputFileLines = Merge-Output `
      -TempLines $TempLines `
      -HashTable $HashTable `
      -ColNames $ColNames `
      -CommentBlock $CommentBlock
    Set-Content -Path $OutputFile -Value $OutputFileLines
  }
  Set-Location -Path $PSScriptRoot
}
